from .age import AgeTable
from .art import ArtTable
from .bmi import BmiTable
from .bp import BpTable
from .fbg import FbgTable
from .fbg_ogtt import FbgOgttTable
from .gender import GenderTable
from .ogtt import OgttTable
from .waist import WaistCircumferenceTable
